name: Deploy to OpenShift

on:
  push:
    branches:
      - main  # Deploy when code is pushed to 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=docker.io/${{ secrets.DOCKER_USERNAME }}/flask-app
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/
          oc version


      - name: Log in to OpenShift
        run: |
          oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOKEN }} --insecure-skip-tls-verify=true
          oc project ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Deploy to OpenShift
        run: |
          IMAGE_NAME=docker.io/${{ secrets.DOCKER_USERNAME }}/flask-app
          IMAGE_TAG=$(git rev-parse --short HEAD)

          oc new-app --name=flask-app --docker-image=$IMAGE_NAME:$IMAGE_TAG --allow-missing-images || oc set image deployment/flask-app flask-app=$IMAGE_NAME:$IMAGE_TAG
          oc expose svc/flask-app

      - name: Check deployment status
        run: |
          oc rollout status deployment/flask-app
          oc get routes
